### ISSUE TITLE
Can't create IOReader

### ISSUE THREAD

**Issue by giacomocaironi** [jamesmunns/postcard#161]
I am trying to read from std::io::Read using CRC. As this feature in not standard I am trying to use Flavors.
However,  I can't create an IOReader as its new() constructor is a private associated function, and if I try to crate the struct directly I can't because I need a SlidingBuffer, which is a private struct.
There is a reason why this is the case or am I missing something?

**Comment by jamesmunns** [comment]
Hi @giacomocaironi, I'm not too familiar with the IOReader, maybe @xgroleau has an idea?

**Comment by xgroleau** [comment]
Hey @giacomocaironi and @jamesmunns I don't see the reason why I've put IOReader `new` as private..... Probably overlooked it since I did not compose them for my usecase.
I think we could just put the `new`from IOReader and `EIOReader` as public which would allow the user to compose the flavors as he see fit.
