### ISSUE TITLE
Deserealizing from a (TCP) Stream

### ISSUE THREAD

**Issue by AntonOellerer** [jamesmunns/postcard#78]
Hey, 
First, thank you for your nice project!
I a currently working on a project communicating via TCP streams, and I am using postcard for data serialization/deserialization.
Afaik, there are no guarantees that a `read()` on a `TcpStream` will give me back the contents of exactly one encoded object, and I do not know the size of the serealized object beforehand.
Is the correct way to receive an object via the construct listed [here](https://docs.rs/postcard/latest/postcard/accumulator/struct.CobsAccumulator.html#examples), or is there a better way I am not seeing?
Best regards
Anton

**Comment by iFreilicht** [comment]
I'm deserializing from a serial stream, byte by byte, in one of my own projects. 

Check out [the definition of BufferedIterator](https://github.com/iFreilicht/arduino-gpio-expander/blob/70cfd038/gpio_actions/src/buffered_iterator.rs#L28) which is a postcard flavor. Together with [TryFromIter](https://github.com/iFreilicht/arduino-gpio-expander/blob/70cfd038/gpio_actions/src/buffered_iterator.rs#L57) and [its blanket implementation](https://github.com/iFreilicht/arduino-gpio-expander/blob/70cfd038/gpio_actions/src/buffered_iterator.rs#L71), you can serialize any `#[derive(Serialize)]` (in my case `Action`) type from an iterator, see its [usage in a simple roundtrip-test](https://github.com/iFreilicht/arduino-gpio-expander/blob/70cfd038/gpio_actions/src/lib.rs#L67) as well as its [usage in actual code](https://github.com/iFreilicht/arduino-gpio-expander/blob/70cfd038/arduino_expander/src/main.rs#L69).

Hope this helps.

I'd rather have all this merged to postcard as well because but I think @jamesmunns doesn't have time to review PRs right now.

**Comment by jamesmunns** [comment]
Thanks for pinging me! I realized I had issue/PR notifications turned off.

I probably wouldn't recommend a flavor - we generally assume the whole message is available or not when serializing or deserializing.

What you probably want is some kind of framing on the line outside of postcard.

We do already have a [CobsAccumulator](https://docs.rs/postcard/latest/postcard/accumulator/struct.CobsAccumulator.html) structure,  which is useful for lossy/error prone mediums, which would include UART, or TCP without TLS, where messages COULD be corrupted or some bytes lost. Having COBS allows you to recover from a corrupted message, when it resynchronizes on the next sentinel zero byte.

If you know you have a reliable medium (like TCP + TLS), you can make a much simpler framing by just having length-prefixed messages. I made a demo for that for a friend [here](https://github.com/jamesmunns/async-postcard-demo/blob/main/src/main.rs).

That does use a flavor for encoding, but you could do it just as easily without.

I've turned my notifications back on, let me know if this helps :).

**Comment by AntonOellerer** [comment]
Thank you for the quick answers!
Just one more question: In your example [here](https://docs.rs/postcard/latest/postcard/accumulator/struct.CobsAccumulator.html#examples), you use `raw_buf` to read from the input, then copy the read part to `buf`, and then its complete content to `window`.
I understand that you need a second slice to deal with remaining bytes after feeding, but why can't you simply declare `let mut window = &buf[..ct]`?

**Comment by jamesmunns** [comment]
I'm not sure if I totally follow (also I wrote that a long time ago), but:

* `buf` is just the portion of `raw_buf` that contains valid data (there is no copy)
* `window` starts off as all of `buf`, but it will "shrink to the right" if it was able to complete a whole message, which means the remaining chunk (say, `raw_buf[..n][..(ct - n)]`, will hold the start of the next frame, which we process in the next iteration of the `'cobs` loop.

**Comment by jamesmunns** [comment]
More graphically, it would look something like this:

```
# before the first loop
raw_buf = [ end of frame 1 | start of frame 2 | invalid ];
window = [ end of frame 1 | start of frame 2 ]

# starting the second iter
window = [ start of frame 2 ]

# end of second iter
window = []

# no third iter
```

**Comment by AntonOellerer** [comment]
Ah sorry, I thought slicing primitives would copy the array.
Nevertheless, I do not understand what `buf` is needed for, as we can just grab a window to `raw_buf` as I understand it?

**Comment by jamesmunns** [comment]
Hi @AntonOellerer, as I show in my code above, we *are* only taking a window. There is no intermediary buffer, only the original one that we received data into. Everything else is a (sub) slice of the original buffer.

I'm going to go ahead and close this, but feel free to re-open it or open a new issue if there is still something to resolve.
